relay:
  mode: managed
  upstream: http://nginx/
  credentials: /work/.relay/credentials.json
  host: 0.0.0.0
  port: 3000

processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000}
  redis: "redis://:${REDIS_PASSWORD}@redis:6379"
logging:
  level: debug
  format: auto
